print("hello what is your name")
name = input('Enter your name: ')
print("hello there " + name)
print("And how old are you")
age = input('How old are you: ')
print()
print("so your name is " + name)
print("and your " + age)
print("well my name is also " + name)
