print("hello what is your name")
name = input()
print("hello there " + name)
print("And how old are you")
age = input()
print()
print("so your name is " + name)
print("and your " + age)
print("well my name is also " + age)
